export function getRequiredElement(documentRef, selector) {
  const element = documentRef.querySelector(selector);

  if (!element) {
    throw new Error(`Thiếu phần tử DOM bắt buộc: ${selector}`);
  }

  return element;
}

export function queryAppDom(documentRef = document) {
  return {
    appShell: getRequiredElement(documentRef, '#appShell'),
    viewer: getRequiredElement(documentRef, '#viewer'),
    viewerSection: getRequiredElement(documentRef, '#viewerSection'),
    viewerNotice: getRequiredElement(documentRef, '#viewerNotice'),
    participantRecordingCountdown: getRequiredElement(documentRef, '#participantRecordingCountdown'),
    aoiOverlay: getRequiredElement(documentRef, '#aoiOverlay'),
    gazeDot: getRequiredElement(documentRef, '#gazeDot'),
    sourceVideo: getRequiredElement(documentRef, '#sourceVideo'),
    miniMap: getRequiredElement(documentRef, '#miniMap'),
    playVideoButton: getRequiredElement(documentRef, '#playVideoButton'),
    resetViewButton: getRequiredElement(documentRef, '#resetViewButton'),
    mouseModeButton: getRequiredElement(documentRef, '#mouseModeButton'),
    webcamModeButton: getRequiredElement(documentRef, '#webcamModeButton'),
    gazeProviderSelect: getRequiredElement(documentRef, '#gazeProviderSelect'),
    gazeEngineStatus: getRequiredElement(documentRef, '#gazeEngineStatus'),
    adminSeeSoMonitorSizeInput: getRequiredElement(documentRef, '#adminSeeSoMonitorSizeInput'),
    adminSeeSoFaceDistanceInput: getRequiredElement(documentRef, '#adminSeeSoFaceDistanceInput'),
    calibrateButton: getRequiredElement(documentRef, '#calibrateButton'),
    accuracyButton: getRequiredElement(documentRef, '#accuracyButton'),
    rawGazeDiagnosticButton: getRequiredElement(documentRef, '#rawGazeDiagnosticButton'),
    rawGazeDiagnosticStatus: getRequiredElement(documentRef, '#rawGazeDiagnosticStatus'),
    calibrationProfileSelect: getRequiredElement(documentRef, '#calibrationProfileSelect'),
    validationPolicySelect: getRequiredElement(documentRef, '#validationPolicySelect'),
    studyVideoSelect: getRequiredElement(documentRef, '#studyVideoSelect'),
    aoiFileInput: getRequiredElement(documentRef, '#aoiFileInput'),
    projectionSelect: getRequiredElement(documentRef, '#projectionSelect'),
    stereoLayoutSelect: getRequiredElement(documentRef, '#stereoLayoutSelect'),
    manualAoiLabelInput: getRequiredElement(documentRef, '#manualAoiLabelInput'),
    manualAoiSizeInput: getRequiredElement(documentRef, '#manualAoiSizeInput'),
    manualAoiColorInput: getRequiredElement(documentRef, '#manualAoiColorInput'),
    addManualAoiButton: getRequiredElement(documentRef, '#addManualAoiButton'),
    drawPolygonAoiButton: getRequiredElement(documentRef, '#drawPolygonAoiButton'),
    finishPolygonAoiButton: getRequiredElement(documentRef, '#finishPolygonAoiButton'),
    cancelPolygonAoiButton: getRequiredElement(documentRef, '#cancelPolygonAoiButton'),
    manualAoiStatus: getRequiredElement(documentRef, '#manualAoiStatus'),
    selectedAoiPanel: getRequiredElement(documentRef, '#selectedAoiPanel'),
    selectedAoiLabelInput: getRequiredElement(documentRef, '#selectedAoiLabelInput'),
    selectedAoiPaddingInput: getRequiredElement(documentRef, '#selectedAoiPaddingInput'),
    selectedAoiColorInput: getRequiredElement(documentRef, '#selectedAoiColorInput'),
    saveSelectedAoiButton: getRequiredElement(documentRef, '#saveSelectedAoiButton'),
    deleteSelectedAoiButton: getRequiredElement(documentRef, '#deleteSelectedAoiButton'),
    recordingFileInput: getRequiredElement(documentRef, '#recordingFileInput'),
    recordButton: getRequiredElement(documentRef, '#recordButton'),
    reviewButton: getRequiredElement(documentRef, '#reviewButton'),
    clearButton: getRequiredElement(documentRef, '#clearButton'),
    exportButton: getRequiredElement(documentRef, '#exportButton'),
    exportStatsCsvButton: getRequiredElement(documentRef, '#exportStatsCsvButton'),
    aoiStatsPanel: getRequiredElement(documentRef, '#aoiStatsPanel'),
    exitAnalyticsButton: getRequiredElement(documentRef, '#exitAnalyticsButton'),
    refreshStatsButton: getRequiredElement(documentRef, '#refreshStatsButton'),
    analyticsClearButton: getRequiredElement(documentRef, '#analyticsClearButton'),
    analyticsExportButton: getRequiredElement(documentRef, '#analyticsExportButton'),
    analyticsExportStatsCsvButton: getRequiredElement(documentRef, '#analyticsExportStatsCsvButton'),
    aoiStatsSummary: getRequiredElement(documentRef, '#aoiStatsSummary'),
    aoiStatsCards: getRequiredElement(documentRef, '#aoiStatsCards'),
    aoiStatsDetails: getRequiredElement(documentRef, '#aoiStatsDetails'),
    aoiStatsTable: getRequiredElement(documentRef, '#aoiStatsTable'),
    gazeHeatmapOverlay: getRequiredElement(documentRef, '#gazeHeatmapOverlay'),
    heatmapRuler: getRequiredElement(documentRef, '#heatmapRuler'),
    heatmapRulerMin: getRequiredElement(documentRef, '#heatmapRulerMin'),
    heatmapRulerMax: getRequiredElement(documentRef, '#heatmapRulerMax'),
    sampleCount: getRequiredElement(documentRef, '#sampleCount'),
    modeLabel: getRequiredElement(documentRef, '#modeLabel'),
    webcamStatusLabel: getRequiredElement(documentRef, '#webcamStatusLabel'),
    accuracyStatusLabel: getRequiredElement(documentRef, '#accuracyStatusLabel'),
    aoiSourceLabel: getRequiredElement(documentRef, '#aoiSourceLabel'),
    screenReadout: getRequiredElement(documentRef, '#screenReadout'),
    cameraReadout: getRequiredElement(documentRef, '#cameraReadout'),
    panoramaReadout: getRequiredElement(documentRef, '#panoramaReadout'),
    hitReadout: getRequiredElement(documentRef, '#hitReadout'),
    gazeQualityReadout: getRequiredElement(documentRef, '#gazeQualityReadout'),
    aoiList: getRequiredElement(documentRef, '#aoiList'),
    controlPanel: getRequiredElement(documentRef, '#controlPanel'),
    participantPanel: getRequiredElement(documentRef, '#participantPanel'),
    adminModeLink: getRequiredElement(documentRef, '#adminModeLink'),
    participantStudyVideoSelect: getRequiredElement(documentRef, '#participantStudyVideoSelect'),
    participantIdInput: getRequiredElement(documentRef, '#participantIdInput'),
    participantNameInput: getRequiredElement(documentRef, '#participantNameInput'),
    participantAgeInput: getRequiredElement(documentRef, '#participantAgeInput'),
    participantConsentInput: getRequiredElement(documentRef, '#participantConsentInput'),
    seeSoMonitorSizeInput: getRequiredElement(documentRef, '#seeSoMonitorSizeInput'),
    seeSoFaceDistanceInput: getRequiredElement(documentRef, '#seeSoFaceDistanceInput'),
    participantStartButton: getRequiredElement(documentRef, '#participantStartButton'),
    participantSessionPanel: getRequiredElement(documentRef, '#participantSessionPanel'),
    participantCalibrateButton: getRequiredElement(documentRef, '#participantCalibrateButton'),
    participantAccuracyButton: getRequiredElement(documentRef, '#participantAccuracyButton'),
    participantRecordButton: getRequiredElement(documentRef, '#participantRecordButton'),
    participantExportButton: getRequiredElement(documentRef, '#participantExportButton'),
    participantResultPanel: getRequiredElement(documentRef, '#participantResultPanel'),
    participantResultSummary: getRequiredElement(documentRef, '#participantResultSummary'),
    participantExportCsvButton: getRequiredElement(documentRef, '#participantExportCsvButton'),
    participantExportJsonButton: getRequiredElement(documentRef, '#participantExportJsonButton'),
    participantExportHeatmapButton: getRequiredElement(documentRef, '#participantExportHeatmapButton'),
    participantUploadStatus: getRequiredElement(documentRef, '#participantUploadStatus'),
    participantFlowSteps: Array.from(documentRef.querySelectorAll('#participantFlowRail .flow-step')),
    adminFlowSteps: Array.from(documentRef.querySelectorAll('#adminWorkflowRail .admin-flow-step')),
    validationTestPanel: getRequiredElement(documentRef, '#validationTestPanel'),
    validationTestStatus: getRequiredElement(documentRef, '#validationTestStatus'),
    validationSeeSoMonitorSizeInput: getRequiredElement(documentRef, '#validationSeeSoMonitorSizeInput'),
    validationSeeSoFaceDistanceInput: getRequiredElement(documentRef, '#validationSeeSoFaceDistanceInput'),
    validationTestCalibrateButton: getRequiredElement(documentRef, '#validationTestCalibrateButton'),
    validationTestAccuracyButton: getRequiredElement(documentRef, '#validationTestAccuracyButton'),
    validationStatsPopup: getRequiredElement(documentRef, '#validationStatsPopup'),
    validationStatsSummary: getRequiredElement(documentRef, '#validationStatsSummary'),
    validationStatsMean: getRequiredElement(documentRef, '#validationStatsMean'),
    validationStatsMedian: getRequiredElement(documentRef, '#validationStatsMedian'),
    validationStatsP90: getRequiredElement(documentRef, '#validationStatsP90'),
    validationStatsMax: getRequiredElement(documentRef, '#validationStatsMax'),
    validationStatsStability: getRequiredElement(documentRef, '#validationStatsStability'),
    validationStatsTargetCount: getRequiredElement(documentRef, '#validationStatsTargetCount'),
    validationStatsCloseButton: getRequiredElement(documentRef, '#validationStatsCloseButton'),
    calibrationOverlay: getRequiredElement(documentRef, '#calibrationOverlay'),
    calibrationTarget: getRequiredElement(documentRef, '#calibrationTarget'),
    calibrationProgress: getRequiredElement(documentRef, '#calibrationProgress'),
    calibrationDescription: getRequiredElement(documentRef, '#calibrationDescription'),
    cancelCalibrationButton: getRequiredElement(documentRef, '#cancelCalibrationButton'),
  };
}
